version: '3.4'

services:
  demoweb:
    container_name: demoweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- VIRTUAL_HOST=dominiodepruebawayni.azurewebsites.net,www.dominiodepruebawayni.azurewebsites.net
      #- LETSENCRYPT_HOST=dominiodepruebawayni.azurewebsites.net,www.dominiodepruebawayni.azurewebsites.net
      #- LETSENCRYPT_EMAIL=antony.torres@wayni.pe
    ports:
      - "80"
      - "443"
    expose:
      - 80
    #volumes:
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    #depends_on:
    #  - nginx-proxy
    #  - letsencrypt
    networks:
      - docker-network
 
#  nginx-proxy:
#    container_name: nginx-proxy
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - certs:/etc/nginx/certs:ro
#      - vhostd:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#    labels:
#      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
#    networks:
#      - docker-network

#  letsencrypt:
#    container_name: letsencrypt
#    restart: always
#    environment:
#      - NGINX_PROXY_CONTAINER=nginx-proxy
#      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
#      #- ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
#    volumes:
#      - certs:/etc/nginx/certs:rw
#      - vhostd:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
#    volumes_from:
#      -  nginx-proxy:rw
#    networks:
#      - docker-network

#volumes: 
#  certs:
#    driver: azure_file
#    driver_opts:
#      share_name: myfileshare
#      storage_account_name: mystorageaccount
#  html:
#    driver: azure_file
#    driver_opts:
#      share_name: myfileshare
#      storage_account_name: mystorageaccount
#  vhostd:
#    driver: azure_file
#    driver_opts:
#      share_name: myfileshare
#      storage_account_name: mystorageaccount

  demoapi:
    container_name: demoapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8082:8082"
      - "8083:8083"
    #volumes:
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
