version: '3.4'

services:
  demoweb:
    container_name: demoweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - VIRTUAL_HOST=dev.wayni.pe,www.dev.wayni.pe
      - LETSENCRYPT_HOST=dev.wayni.pe,www.dev.wayni.pe
      - LETSENCRYPT_EMAIL=antony.torres@wayni.pe
    expose:
      - 80
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - nginx-proxy
      - letsencrypt
    networks:
      - docker-network
 
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - docker-network

  letsencrypt:
    container_name: letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      #- ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
    volumes_from:
      -  nginx-proxy:rw
    networks:
      - docker-network

volumes: 
  certs:
  html:
  vhostd:

networks:
  docker-network:
    driver: bridge